logging:
  level:
    '[org.springframework.cloud.config]': debug
server:
  port: 8888
spring:
  application:
    name: cs-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Spyron1234/microservice-config-repo
          skipSslValidation: true
          searchPaths: '{application}'
          basedir: D:\\STS_WORKSPACE\\MSERV2\\git
          cloneOnStart: true