logging:
  level:
    '[org.springframework.cloud.config]': debug
server:
  port: 8889
spring:
#  rabbitmq:
#    host: "localhost"
#    username: "guest"
#    password: "guest"
#    port: 5672
  application:
    name: cs-config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: "classpath:/config"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Spyron1234/microservice-config-repo
          skipSslValidation: true
          searchPaths: '{application}'
          basedir: D:\\STS_WORKSPACE\\MSERV2\\git
          cloneOnStart: true
          default-label: main
          timeout: 5
#encrypt:
#  key: "89YUHE45WmjkA868RE"
management:
  endpoints:
    web:
      exposure:
        include: "*"